apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiproduct
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apiproduct
  template:
    metadata:
      labels:
        app: apiproduct
    spec:
      containers:
        - name: apiproduct
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
