apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apiproduct-gateway
  namespace: desenvolvimento
spec:
  selector:
    istio: ingressgateway  # Este é o padrão usado no istio-system
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"