# templates/virtualservice.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: apiproduct.desenvolvimento.svc.cluster.local
            port:
              number: 8080