replicaCount: 1

image:
  repository: apiproduct
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30000
env:
  ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Database=ayla;User Id=sa;Password=123testPass@;TrustServerCertificate=True;"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
